stages:
  - build
  - test
  - deploy

buildApp:
  stage: build
  image: maven
  cache:
    paths:
      - .m2/repository
      - target/
  script:
    - 'mvn clean'

deployApp:
  stage: deploy
  image: maven
  cache:
    paths:
      - .m2/repository
      - target/
  script:
    - 'echo $IP'
    - 'echo $USERD'
    - 'export IP=$IP'
    - 'export USERD=$USERD'
    - 'export PASSWORD=$PASS'
    - 'mvn install tomcat7:deploy'


