stages:
  - build
  - test
  - deploy

cache:
  paths:
    - ./.m2/repository

buildApp:
  stage: build
  image: maven
  script:
    - 'mvn clean install'

deployApp:
  stage: deploy
  image: maven
  script:
    - 'echo $IP'
    - 'echo $USERD'
    - 'export IP=$IP'
    - 'export USERD=$USERD'
    - 'export PASSWORD=$PASS'
    - 'mvn install'
    - 'cd .. && ls'
    #- 'mvn install tomcat7:deploy'


