stages:
  - build
  - test
  - deploy

buildApp:
  stage: build
  image: maven
  cache:
    paths:
      - ./.m2
  script:
    - 'mvn clean install'

deployApp:
  stage: deploy
  image: maven
  script:
    - 'echo $IP'
    - 'echo $USERD'
    - 'export IP=$IP'
    - 'export USERD=$USERD'
    - 'export PASSWORD=$PASS'
    - 'mvn install'
    - 'cd .. && ls'
    #- 'mvn install tomcat7:deploy'


